#ifndef _COMMONDEFS_
#define _COMMONDEFS_

#define MAXMEMBYTES 256
#define STACKCAPACITY 256
#define MAXREGS 16
#define MAXOPCODES 27
#define BUFFERLENGTH 256
#define MAXOPERANDLENGTH 3

enum {
	CC_LE,//REG1 < REG2  IN CMP A B
	CC_EQ,//REG1 == REG2  IN CMP A B
	CC_GT,//REG1 > REG2  IN CMP A B
	CC_MISC
};


enum {
	HLT_CODE = 0,
	ADD2_CODE = 1,
	SUB2_CODE = 2,
	JNZ_CODE = 3,
	JZ_CODE = 4,
	MOV_CODE = 5,
	LOAD_CODE = 6,
	LDR_CODE = 7,
	STORE_CODE = 8,
	STR_CODE = 9,
	INC_CODE = 10,
	DCR_CODE = 11,
	MVI_CODE = 12,
	ADD3_CODE = 13,
	SUB3_CODE = 14,
	DISP_CODE = 15,
	ADD1_CODE = 16,
	SUB1_CODE = 17,

	PUSH_CODE = 18,
	POP_CODE = 19,

	CALL_CODE = 20,
	RET_CODE = 21,

	CMP_CODE = 22,
	JLT_CODE = 23,
	JEQ_CODE = 24,
	JGT_CODE = 25,
	JNEQ_CODE = 26
};

enum {
	HLT_CODE_LENGTH = 1,
	ADD2_CODE_LENGTH = 3,
	SUB2_CODE_LENGTH = 3,
	ADD3_CODE_LENGTH = 4,
	SUB3_CODE_LENGTH = 4,
	JNZ_CODE_LENGTH = 2,
	JZ_CODE_LENGTH = 2,
	MOV_CODE_LENGTH = 3,
	LOAD_CODE_LENGTH = 3,
	LDR_CODE_LENGTH = 3,
	STORE_CODE_LENGTH = 3,
	STR_CODE_LENGTH = 3,
	INC_CODE_LENGTH = 2,
	DCR_CODE_LENGTH = 2,
	MVI_CODE_LENGTH = 3,
	DISP_CODE_LENGTH = 2,
	ADD1_CODE_LENGTH = 2,
	SUB1_CODE_LENGTH = 2,
	PUSH_CODE_LENGTH = 2,
	POP_CODE_LENGTH = 2,
	CALL_CODE_LENGTH = 2,
	RET_CODE_LENGTH = 1,
	CMP_CODE_LENGTH = 3,
	JLT_CODE_LENGTH = 2,
	JEQ_CODE_LENGTH = 2,
	JGT_CODE_LENGTH = 2,
	JNEQ_CODE_LENGTH = 2
};

#endif
