#ifndef _COMMONDEFS_
#define _COMMONDEFS_

#define MAXMEMBYTES 256
#define MAXREGS 16
#define MAXOPCODES 16
#define BUFFERLENGTH 256
#define MAXOPERANDLENGTH 3

enum {
	HLT_CODE = 0,
	ADD2_CODE = 1,
	SUB2_CODE = 2,
	JNZ_CODE = 3,
	JZ_CODE = 4,
	MOV_CODE = 5,
	LOAD_CODE = 6,
	LDR_CODE = 7,
	STORE_CODE = 8,
	STR_CODE = 9,
	INC_CODE = 10,
	DCR_CODE = 11,
	MVI_CODE = 12,
	ADD3_CODE = 13,
	SUB3_CODE = 14,
	DISP_CODE = 15
};

enum {
	HLT_CODE_LENGTH = 1,
	ADD2_CODE_LENGTH = 3,
	SUB2_CODE_LENGTH = 3,
	ADD3_CODE_LENGTH = 4,
	SUB3_CODE_LENGTH = 4,
	JNZ_CODE_LENGTH = 2,
	JZ_CODE_LENGTH = 2,
	MOV_CODE_LENGTH = 3,
	LOAD_CODE_LENGTH = 3,
	LDR_CODE_LENGTH = 3,
	STORE_CODE_LENGTH = 3,
	STR_CODE_LENGTH = 3,
	INC_CODE_LENGTH = 2,
	DCR_CODE_LENGTH = 2,
	MVI_CODE_LENGTH = 3,
	DISP_CODE_LENGTH = 2
};

#endif
